(in-package :cl-user)

(defpackage :paymill 
  (:use :cl)
  (:nicknames :pml)
  (:export 
   ;; error reporting
   "PAYMILL-ERROR" "PAYMILL-GENERAL-ERROR" "PAYMILL-BAD-REQUEST"
   "PAYMILL-UNAUTHORIZED" "PAYMILL-TRANSACTION-ERROR" "PAYMILL-NOT-FOUND"
   "PAYMILL-PRECONDITION-FAILED" "PAYMILL-SERVER-ERROR"
   "API-INTERNAL-ERROR" "SIGNAL-PAYMILL-ERROR"
   ;;resources
   "USE-KEY" "CLIENTS" "OFFERS" "PAYMENTS" 
   "TRANSACTIONS" "REFUNDS" "SUBSCRIPTIONS"))
